import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/query-client";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/common/theme-provider";
import { cookies } from "next/headers";
import ClientInitializer from "@/components/ClientInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Prueba xDevelop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();

  const role = cookieStore.get("role")?.value ?? null;
  const accessToken = cookieStore.get("accessToken")?.value ?? null;
  const userId = cookieStore.get("userId")?.value ?? null;

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={true}
          disableTransitionOnChange={true}
        >
          <QueryProvider>
            <ClientInitializer
              role={role as "admin" | "user" | null}
              accessToken={accessToken}
              userId={Number(userId)}
            />
            {children}
          </QueryProvider>
          <Toaster position="top-right" />
        </ThemeProvider>
      </body>
    </html>
  );
}
